# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fAahoKS0tUluWNQJyU0c9Hs3i27j1WC1I9mBf1MqbceMx/meCYurj9bG+uWuyLmiPpKEh0y5bipd5a7JAL2N/dEbnvHpgms2e2KllvK/2aZomehnguRX3igpT5PckBjKmUHHuOpjE3UNtPe+zki7enlnWuEY+Mv7p6CtLonMNXLNuRFi0x2+lJM0HMZ5kUpHqmVfEOXHVbLYybamhMBhYcLcrKVgj2etz2pd+v4HKzDXjpXgw5lSyXPkq+GiVwdx23iq+C2Xfq2iK4JM7mBVxesXVD5WecMRBGFP2dKJlZyySnfryFYKB/0mk07+2rWNUARTUl82xIc8nHJ6i9tedwErAR2og5FkKBd4rImK1Bi6CBcMU6gyil/DX5fUJtWTWc7WH96lC+2JmnlQZJd13Q4VkIAP2PSKaxcUJm29bou45k3QIbE6Gic7fHohytYrA+dNlNTKEqp5CSc5LhWlHlN/QEwOxhPsYG0/KFdo3R2E11Dn8Ew06kvlvr5nMxeO5uBUKgAtLic76QE/S/0W4shgiisn+68JNDJVnCUSIkK6hg5Gxqjh++4NKMVQjUm05KQ7GF9PvCom1kueyRoZ2PediRtryigUemB6HFvBtVTS3AlVFJZQ1dQNVsUljo8bLgNNDmMXc1sqAPoG71FyyqW/3xhnf1HLjppFZN/64Ec="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
