travis:
  secure:
    BINSTAR_TOKEN: fAahoKS0tUluWNQJyU0c9Hs3i27j1WC1I9mBf1MqbceMx/meCYurj9bG+uWuyLmiPpKEh0y5bipd5a7JAL2N/dEbnvHpgms2e2KllvK/2aZomehnguRX3igpT5PckBjKmUHHuOpjE3UNtPe+zki7enlnWuEY+Mv7p6CtLonMNXLNuRFi0x2+lJM0HMZ5kUpHqmVfEOXHVbLYybamhMBhYcLcrKVgj2etz2pd+v4HKzDXjpXgw5lSyXPkq+GiVwdx23iq+C2Xfq2iK4JM7mBVxesXVD5WecMRBGFP2dKJlZyySnfryFYKB/0mk07+2rWNUARTUl82xIc8nHJ6i9tedwErAR2og5FkKBd4rImK1Bi6CBcMU6gyil/DX5fUJtWTWc7WH96lC+2JmnlQZJd13Q4VkIAP2PSKaxcUJm29bou45k3QIbE6Gic7fHohytYrA+dNlNTKEqp5CSc5LhWlHlN/QEwOxhPsYG0/KFdo3R2E11Dn8Ew06kvlvr5nMxeO5uBUKgAtLic76QE/S/0W4shgiisn+68JNDJVnCUSIkK6hg5Gxqjh++4NKMVQjUm05KQ7GF9PvCom1kueyRoZ2PediRtryigUemB6HFvBtVTS3AlVFJZQ1dQNVsUljo8bLgNNDmMXc1sqAPoG71FyyqW/3xhnf1HLjppFZN/64Ec=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
