travis:
  secure:
    BINSTAR_TOKEN: VIxJY5i3/fF8ItMvI6eWV658EFpRSb/Xf+aKFEm5tsYaRS8y73zlZUMd6Zk+7tp8QkjaGFrd6EOG8ILKYd9BIjTuUlHv1fvd/BYCr/2tCNH5+BXnbMIkxFpOH1xfxrmYzw1HX6DWtS1D5GqK/fEEJVBWKDBg1CBLleG8mjsdOMOE1S0s80NzDgaTV5KXOGRVdhkHJ4jB/650jC9Jjl46PrbRoU3nODiNmAzy4sFxGdVs3xZ6rZNyzGTmd6lMpW1Ab7HocV7B6cC0IeiSahtiqw+BwwhncI9ezEdv4uPMvTtg4arjxCN8mjpMJDNU5nFONhKKs9Rn6X0MO7H9tFNxzNWA1X0nb2az7LYah3g9N3PN11tSLKwIQ/Ba/CFzq1qJIm/VFY5iaOUNNwz099R16/sLUrBQ2ioYVOLkoumLcVDKcIhcQYEM221Df/cE0Qc4zFKDFvMbWalg8hDyOyrvA7TNQPwxiMKaizEo7GiAeV4vORSOLY4PiVw6hVBKLtLNLefIYalxGp26jV7V6iynWQDhGVwTk6TP+b+aUIVkB7Ggn8U8EU86j6KSmPfmo8Lq6CKvlSETeTXw0Qlxcw/dL0AnpERpQ0DMwUR9Ua0eF7uL3eduIIcEfmkzSpyoKj9lhSJ2X/Yq1wUn+gpcaEotHzibTb8yWs249OEnArQc1os=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
